<?php


use gcf\utils\XMLConfig;
use PHPUnit\Framework\TestCase;

class XMLParseTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws Exception
     */
    public function testConfigLlistatsXML()
    {
        $config = XMLConfig::GetListConfigFromXML("../frontal/xmls/llistats_costs.xml");
    }
}