name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Setup enviroment
      run: |
          phpVersion=8.1
          sudo apt-get -y update
          sudo update-alternatives --set php /usr/bin/php8.1
          sudo update-alternatives --set phar /usr/bin/phar8.1
          sudo update-alternatives --set phpdbg /usr/bin/phpdbg8.1
          sudo update-alternatives --set php-cgi /usr/bin/php-cgi8.1
          sudo update-alternatives --set phar.phar /usr/bin/phar.phar8.1
          sudo apt -y update
          sudo apt -y install gearman-job-server libgearman8 php8.1-imagick php8.1-interbase php8.1-gearman php8.1-soap php8.1-mbstring babel-minify
          php -version
    
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
